apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-frontend
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: httpd-container
          image: httpd:2.4-alpine
